### ISSUE TITLE
enable firewall and add the proper ports

### ISSUE THREAD

**Issue by bbaassssiiee** [kouji-kojima-ansible/el7-desktop#1]
Disabling the firewall does not comply with our standard, can't you just add the ports?

**Comment by bbaassssiiee** [comment]
https://github.com/kouji-kojima-ansible/el7-desktop/blob/ba279b647cec420f5a59bc8ebd6a97f2583622c8/tasks/main.yml#L68

**Comment by kouji-kojima** [comment]
thanks :)
